# Rubocop configuration

inherit_from: .rubocop_todo.yml

# Team preferences different from Rubocop defaults:
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/ClassCheck:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# Because an SnmpServer cannot be destroyed, we end most of the SnmpServer
# test cases by explicitly returning the configuration to default.
# Rubocop thinks this is a no-op but it isn't.
Lint/UselessSetterCall:
  Exclude:
    - 'tests/test_snmpserver.rb'