# Rubocop configuration

inherit_from: .rubocop_todo.yml

Style/TrailingComma:
  # TODO instead of turning this off, maybe set:
  # EnforcedStyleForMultiline: consistent_comma
  Enabled: false

# Because an SnmpServer cannot be destroyed, we end most of the SnmpServer
# test cases by explicitly returning the configuration to default.
# Rubocop thinks this is a no-op but it isn't.
Lint/UselessSetterCall:
  Exclude:
    - 'tests/test_snmpserver.rb'